package state

import state.gen.*

// may be autogenerated

/*
    1) чтобы можно было по юзеру авторизовать
    2) чтобы можно было get без последствий, а потом когда set, то создавалось
       (а что вложенный get???)

    val GameStateDiff?.entities: EntityStateDiff?
        get() = this?.entities
        put() =
    val PlayerStateDiff?.чета
     */

var MobState.x: Dimension
    get() = this.position.x
    set(value) { this.position.x = value }


var MobState.y: Dimension
    get() = this.position.y
    set(value) { this.position.y = value }

val EMPTY_GAMESTATE_DIFF_GENERATOR = {
    GameStateDiff(mutableMapOf(), mutableMapOf(), mutableMapOf(), null)
}

operator fun ((GameStateDiff) -> Unit).invoke(gameState: GameState) {
    val tempDiff = EMPTY_GAMESTATE_DIFF_GENERATOR()
    invoke(tempDiff)
    gameState.plusAssign(tempDiff)
}
