package state

import state.gen.*

// may be autogenerated

fun GameStateDiff.getPlayer(playerId: String): PlayerStateDiff? {
    /*
    1) чтобы можно было по юзеру авторизовать
    2) чтобы можно было get без последствий, а потом когда set, то создавалось
       (а что вложенный get???)

    val GameStateDiff?.entities: EntityStateDiff?
        get() = this?.entities
        put() =
    val PlayerStateDiff?.чета
     */


    return entities[playerId] as PlayerStateDiff?
}

fun GameState.getPlayer(playerId: String): PlayerState {
    return entities.getValue(playerId) as PlayerState
}

fun ImmutableGameState.getPlayer(playerId: String): ImmutablePlayerState {
    return entities.getValue(playerId) as ImmutablePlayerState
}

var MobState.x: Dimension
    get() = this.position.x
    set(value) { this.position.x = value }


var MobState.y: Dimension
    get() = this.position.y
    set(value) { this.position.y = value }
